name: Terraform Plan

on:
  pull_request:
    branches:
      - dev
      - stage
      - main

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  terraform-plan:
    name: Terraform Init & Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Plan All Modules
        run: |
          set -e
          BASE_DIR=./envs/${{ github.base_ref }}
          OUTPUT_FILE=all_plans.txt
          echo "" > $OUTPUT_FILE

          for DIR in $(find "$BASE_DIR" -maxdepth 1 -mindepth 1 -type d); do
            echo "===== Terraform Plan in $DIR =====" | tee -a $OUTPUT_FILE
            cd "$DIR"
            terraform init -backend-config=../../backend/backend.tf
            terraform validate | tee -a ../../$OUTPUT_FILE
            terraform plan -no-color -out=tfplan | tee -a ../../$OUTPUT_FILE
            terraform show -no-color tfplan | tee -a ../../$OUTPUT_FILE
            cd - > /dev/null
            echo "" >> ../../$OUTPUT_FILE
          done

      - name: Comment Plan on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: ./envs/${{ github.base_ref }}/all_plans.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
